server {
  listen 3000;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  include /etc/nginx/csp.conf;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(js|css|json|svg|ico|woff2?)$ {
    try_files $uri =404;
  }
}
